import connectDB from "@/lib/db"
import { GoogleGenAI } from "@google/genai";
import { resolveProductImage } from "@/lib/product-images";
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});
async function generateVector(text) {
  const response = await ai.models.embedContent({
    model: "gemini-embedding-001",
    contents: text,
  });

  return response.embeddings[0].values;
}
import product from "@/models/Product"

export async function GET() {
  await connectDB();
  await product.deleteMany();

  const products = [
    {
      title: "Blue Sneakers",
      description: "Comfortable and stylish sneakers for everyday wear.",
      Price: 79.99,
      Category: "Footwear",
      image: "public/shoes.jpg",
    },
    {
      title: "Wireless Headphones",
      description: "High-quality wireless headphones with noise cancellation.",
      Price: 149.99,
      Category: "Electronics",
      image: "public/headphones.jpg",
    },
    {
      title: "Smartwatch",
      description: "A sleek smartwatch with fitness tracking and notifications.",
      Price: 199.99,
      Category: "Wearables",
      image: "public/smartwatch.jpg",
    },
    {
      title: "Leather Wallet",
      description: "A premium leather wallet with multiple card slots.",
      Price: 49.99,
      Category: "Accessories",
      image: "public/belt.jpg",
    },
    {
      title: "Gaming Laptop",
      description: "A powerful gaming laptop with high-end graphics and performance.",
      Price: 1299.99,
      Category: "Computers",
      image: "public/keyboard.png",
    },
    {
      title: "Fitness Tracker",
      description: "A compact fitness tracker to monitor your daily activity and health.",
      Price: 59.99,
      Category: "Wearables",
      image: "public/smartwatch.jpg",
    },
    {
      title: "Bluetooth Speaker",
      description: "Portable Bluetooth speaker with immersive sound quality.",
      Price: 89.99,
      Category: "Electronics",
      image: "public/speaker.jpg",
    },
    {
      title: "Sunglasses",
      description: "Stylish sunglasses with UV protection.",
      Price: 29.99,
      Category: "Accessories",
      image: "public/sunglasses.jpg",
    },
    {
      title: "Digital Camera",
      description: "Capture stunning photos with this high-resolution camera.",
      Price: 499.99,
      Category: "Electronics",
      image: "public/camera.jpg",
    },
    {
      title: "Running Shoes",
      description: "Lightweight running shoes designed for comfort.",
      Price: 99.99,
      Category: "Footwear",
      image: "public/shoes.jpg",
    },
    {
      title: "Backpack",
      description: "Durable backpack with spacious compartments.",
      Price: 69.99,
      Category: "Accessories",
      image: "public/bag.jpg",
    },
    {
      title: "Tablet",
      description: "Powerful tablet for work, entertainment, and creativity.",
      Price: 399.99,
      Category: "Electronics",
      image: "public/smartphone.jpg",
    },
    {
      title: "Smartphone",
      description: "Feature-packed smartphone with an amazing display.",
      Price: 899.99,
      Category: "Electronics",
      image: "public/smartphone.jpg",
    },
    {
      title: "Wireless Earbuds",
      description: "Compact earbuds with crystal-clear audio.",
      Price: 129.99,
      Category: "Electronics",
      image: "public/headphones.jpg",
    },
    {
      title: "Coffee Maker",
      description: "Automatic coffee maker for delicious coffee every morning.",
      Price: 79.99,
      Category: "Home Appliances",
      image: "public/coffee.jpg",
    },
    {
      title: "Electric Toothbrush",
      description: "Rechargeable toothbrush for superior oral hygiene.",
      Price: 59.99,
      Category: "Personal Care",
      image: "public/toothbrush.jpg",
    },
    {
      title: "Office Chair",
      description: "Ergonomic office chair with lumbar support.",
      Price: 219.99,
      Category: "Furniture",
      image: "public/led.jpg",
    },
    {
      title: "Mechanical Keyboard",
      description: "RGB mechanical keyboard with tactile switches.",
      Price: 109.99,
      Category: "Computers",
      image: "public/keyboard.png",
    },
    {
      title: "Gaming Mouse",
      description: "High-precision gaming mouse with customizable DPI.",
      Price: 59.99,
      Category: "Computers",
      image: "public/keyboard.png",
    },
    {
      title: "27-inch Monitor",
      description: "Full HD IPS monitor with vibrant colors.",
      Price: 249.99,
      Category: "Computers",
      image: "public/keyboard.png",
    },
    {
      title: "External SSD",
      description: "Fast portable SSD with 1TB storage capacity.",
      Price: 159.99,
      Category: "Storage",
      image: "public/keyboard.png",
    },
    {
      title: "USB-C Hub",
      description: "Multi-port USB-C hub for laptops and tablets.",
      Price: 39.99,
      Category: "Accessories",
      image: "public/keyboard.png",
    },
    {
      title: "Portable Charger",
      description: "10000mAh power bank with fast charging.",
      Price: 44.99,
      Category: "Electronics",
      image: "public/keyboard.png",
    },
    {
      title: "Air Fryer",
      description: "Healthy cooking with little to no oil.",
      Price: 139.99,
      Category: "Home Appliances",
      image: "public/cooker.jpg",
    },
    {
      title: "Vacuum Cleaner",
      description: "Powerful vacuum cleaner for effortless cleaning.",
      Price: 189.99,
      Category: "Home Appliances",
      image: "public/vaccum.jpg",
    },
    {
      title: "Microwave Oven",
      description: "Compact microwave oven with multiple cooking modes.",
      Price: 159.99,
      Category: "Home Appliances",
      image: "public/cooker.jpg",
    },
    {
      title: "Electric Kettle",
      description: "Fast-boiling electric kettle with auto shut-off.",
      Price: 34.99,
      Category: "Kitchen",
      image: "public/coffee.jpg",
    },
    {
      title: "Blender",
      description: "High-speed blender perfect for smoothies and shakes.",
      Price: 69.99,
      Category: "Kitchen",
      image: "public/cooker.jpg",
    },
    {
      title: "Yoga Mat",
      description: "Non-slip yoga mat for workouts and meditation.",
      Price: 24.99,
      Category: "Fitness",
      image: "public/yoga.jpg",
    },
    {
      title: "Dumbbell Set",
      description: "Adjustable dumbbell set for strength training.",
      Price: 119.99,
      Category: "Fitness",
      image: "public/yoga.jpg",
    },
    {
      title: "Camping Tent",
      description: "Waterproof 4-person camping tent.",
      Price: 229.99,
      Category: "Outdoor",
      image: "public/basket.jpg",
    },
    {
      title: "Travel Suitcase",
      description: "Lightweight hard-shell suitcase with spinner wheels.",
      Price: 139.99,
      Category: "Travel",
      image: "public/bag.jpg",
    },
    {
      title: "Winter Jacket",
      description: "Warm and stylish insulated winter jacket.",
      Price: 179.99,
      Category: "Clothing",
      image: "public/jacket.jpg",
    },
    {
      title: "Classic Wrist Watch",
      description: "Elegant analog watch with leather strap.",
      Price: 149.99,
      Category: "Accessories",
      image: "public/smartwatch.jpg",
    },
    {
      title: "Desk Lamp",
      description: "LED desk lamp with adjustable brightness.",
      Price: 49.99,
      Category: "Home Decor",
      image: "public/led.jpg",
    },
    {
      title: "Bookshelf",
      description: "Modern wooden bookshelf with five shelves.",
      Price: 169.99,
      Category: "Furniture",
      image: "public/led.jpg",
    },
    {
      title: "Wall Clock",
      description: "Minimalist wall clock for home and office.",
      Price: 29.99,
      Category: "Home Decor",
      image: "public/led.jpg",
    },
    {
      title: "Perfume",
      description: "Long-lasting fragrance with a refreshing scent.",
      Price: 89.99,
      Category: "Personal Care",
      image: "public/perfume.jpg",
    },
    {
      title: "Hair Dryer",
      description: "Professional hair dryer with multiple heat settings.",
      Price: 64.99,
      Category: "Personal Care",
      image: "public/hair.jpg",
    },
    {
      title: "Electric Shaver",
      description: "Cordless electric shaver for a smooth shave.",
      Price: 84.99,
      Category: "Personal Care",
      image: "public/toothbrush.jpg",
    },
    {
      title: "Men's Formal Blazer",
      description: "Slim-fit formal blazer perfect for office meetings and wedding occasions.",
      Price: 159.99,
      Category: "Clothing",
      image: "public/jacket.jpg",
    },
    {
      title: "Women's Silk Saree",
      description: "Elegant silk saree with traditional woven design for festive wear.",
      Price: 249.99,
      Category: "Clothing",
      image: "public/saree.jpg",
    },
    {
      title: "Party Wear Salwar Suit",
      description: "Designer embroidered salwar suit for weddings and celebrations.",
      Price: 139.99,
      Category: "Clothing",
      image: "public/saree.jpg",
    },
    {
      title: "Bridal Lehenga",
      description: "Premium bridal lehenga with intricate embroidery and matching dupatta.",
      Price: 699.99,
      Category: "Clothing",
      image: "public/saree.jpg",
    },
    {
      title: "Men's Sherwani",
      description: "Traditional sherwani crafted for weddings and festive occasions.",
      Price: 299.99,
      Category: "Clothing",
      image: "hpublic/saree.jpg",
    },
    {
      title: "Women's Denim Jacket",
      description: "Stylish denim jacket suitable for casual outings.",
      Price: 89.99,
      Category: "Clothing",
      image: "public/jacket.jpg",
    },
    {
      title: "Men's Hoodie",
      description: "Warm fleece hoodie designed for winter comfort.",
      Price: 64.99,
      Category: "Clothing",
      image: "public/jacket.jpg",
    },
    {
      title: "Graphic T-Shirt",
      description: "Soft cotton graphic t-shirt for everyday casual wear.",
      Price: 24.99,
      Category: "Clothing",
      image: "public/jacket.jpg",
    },
    {
      title: "Women's Palazzo Pants",
      description: "Comfortable palazzo pants with elegant fit.",
      Price: 39.99,
      Category: "Clothing",
      image: "public/jacket.jpg",
    },
    {
      title: "Men's Chinos",
      description: "Stretchable chino pants suitable for office and casual wear.",
      Price: 54.99,
      Category: "Clothing",
      image: "public/jacket.jpg",
    },
    {
      title: "Leather Belt",
      description: "Classic leather belt with durable metal buckle.",
      Price: 29.99,
      Category: "Accessories",
      image: "public/belt.jpg",
    },
    {
      title: "Luxury Handbag",
      description: "Premium handbag with spacious compartments.",
      Price: 119.99,
      Category: "Accessories",
      image: "public/handbag.jpg",
    },
    {
      title: "Silver Bracelet",
      description: "Elegant silver bracelet for everyday fashion.",
      Price: 59.99,
      Category: "Jewellery",
      image: "public/jwelery.jpg",
    },
    {
      title: "Gold Plated Necklace",
      description: "Beautiful gold-plated necklace for festive occasions.",
      Price: 99.99,
      Category: "Jewellery",
      image: "public/jwelery.jpg",
    },
    {
      title: "Diamond Earrings",
      description: "Sparkling earrings with premium craftsmanship.",
      Price: 249.99,
      Category: "Jewellery",
      image: "public/jwelery.jpg",
    },
    {
      title: "Women's Ring Set",
      description: "Fashion ring set with elegant stone finish.",
      Price: 44.99,
      Category: "Jewellery",
      image: "public/jwelery.jpg",
    },
    {
      title: "Sports Cap",
      description: "Breathable sports cap with adjustable strap.",
      Price: 19.99,
      Category: "Accessories",
      image: "public/cap.jpg",
    },
    {
      title: "Beanie Hat",
      description: "Warm knitted beanie ideal for cold weather.",
      Price: 22.99,
      Category: "Accessories",
      image: "public/cap.jpg",
    },
    {
      title: "Travel Duffel Bag",
      description: "Large waterproof duffel bag for travel and gym.",
      Price: 74.99,
      Category: "Travel",
      image: "public/bag.jpg",
    },
    {
      title: "Laptop Backpack",
      description: "Anti-theft backpack with dedicated laptop compartment.",
      Price: 84.99,
      Category: "Accessories",
      image: "public/bag.jpg",
    },
    {
      title: "Running Shorts",
      description: "Lightweight running shorts with moisture-wicking fabric.",
      Price: 29.99,
      Category: "Fitness",
      image: "public/jacket.jpg",
    },
    {
      title: "Compression T-Shirt",
      description: "Stretch-fit compression shirt for workouts.",
      Price: 34.99,
      Category: "Fitness",
      image: "public/jacket.jpg",
    },
    {
      title: "Gym Gloves",
      description: "Padded gloves for weightlifting and gym sessions.",
      Price: 24.99,
      Category: "Fitness",
      image: "public/yoga.jpg",
    },
    {
      title: "Resistance Bands",
      description: "Exercise resistance bands for strength training.",
      Price: 19.99,
      Category: "Fitness",
      image: "public/yoga.jpg",
    },
    {
      title: "Foam Roller",
      description: "High-density foam roller for muscle recovery.",
      Price: 32.99,
      Category: "Fitness",
      image: "public/yoga.jpg",
    },
    {
      title: "Lipstick Set",
      description: "Long-lasting matte lipstick collection with vibrant shades.",
      Price: 49.99,
      Category: "Beauty",
      image: "public/lipstic.jpg",
    },
    {
      title: "Makeup Kit",
      description: "Complete makeup kit with essential beauty products.",
      Price: 119.99,
      Category: "Beauty",
      image: "public/makeup.jpg",
    },
    {
      title: "Foundation Cream",
      description: "Smooth liquid foundation with natural finish.",
      Price: 34.99,
      Category: "Beauty",
      image: "public/serum.jpg",
    },
    {
      title: "Face Serum",
      description: "Vitamin C face serum for glowing skin.",
      Price: 29.99,
      Category: "Beauty",
      image: "public/serum.jpg",
    },
    {
      title: "Sunscreen SPF 50",
      description: "Broad-spectrum sunscreen for daily UV protection.",
      Price: 27.99,
      Category: "Beauty",
      image: "public/serum.jpg",
    },
    {
      title: "Body Lotion",
      description: "Hydrating body lotion enriched with aloe vera.",
      Price: 18.99,
      Category: "Beauty",
      image: "public/serum.jpg",
    },
    {
      title: "Face Wash",
      description: "Refreshing facial cleanser suitable for all skin types.",
      Price: 14.99,
      Category: "Beauty",
      image: "public/serum.jpg",
    },
    {
      title: "Hair Straightener",
      description: "Ceramic hair straightener with adjustable temperature.",
      Price: 69.99,
      Category: "Beauty",
      image: "public/hair.jpg",
    },
    {
      title: "Curling Iron",
      description: "Professional curling iron for salon-style curls.",
      Price: 64.99,
      Category: "Beauty",
      image: "public/hair.jpg",
    },
    {
      title: "Nail Polish Set",
      description: "Colorful nail polish collection with glossy finish.",
      Price: 22.99,
      Category: "Beauty",
      image: "public/lipstic.jpg",
    },
    {
      title: "Formal Oxford Shoes",
      description: "Premium leather Oxford shoes for office and events.",
      Price: 149.99,
      Category: "Footwear",
      image: "public/shoes.jpg",
    },
    {
      title: "High Heel Sandals",
      description: "Elegant high heel sandals for parties and weddings.",
      Price: 89.99,
      Category: "Footwear",
      image: "public/sandals.jpg",
    },
    {
      title: "Casual Loafers",
      description: "Comfortable slip-on loafers for daily use.",
      Price: 79.99,
      Category: "Footwear",
      image: "public/shoes.jpg",
    },
    {
      title: "Hiking Boots",
      description: "Water-resistant hiking boots with superior grip.",
      Price: 159.99,
      Category: "Footwear",
      image: "public/shoes.jpg",
    },
    {
      title: "Flip Flops",
      description: "Lightweight flip flops for beach and casual wear.",
      Price: 19.99,
      Category: "Footwear",
      image: "public/sandals.jpg",
    },
    {
      title: "Beach Hat",
      description: "Wide-brim beach hat with UV protection.",
      Price: 24.99,
      Category: "Accessories",
      image: "public/cap.jpg",
    },
    {
      title: "Travel Pillow",
      description: "Memory foam neck pillow for comfortable journeys.",
      Price: 29.99,
      Category: "Travel",
      image: "public/bag.jpg",
    },
    {
      title: "Passport Holder",
      description: "Premium passport holder with RFID protection.",
      Price: 21.99,
      Category: "Travel",
      image: "public/bag.jpg",
    },
    {
      title: "Portable Neck Fan",
      description: "Rechargeable wearable neck fan for outdoor activities.",
      Price: 34.99,
      Category: "Electronics",
      image: "public/fan.jpg",
    },
    {
      title: "Smart LED Bulb",
      description: "Wi-Fi enabled smart bulb with app control.",
      Price: 24.99,
      Category: "Home Appliances",
      image: "public/led.jpg",
    },
    {
      title: "Electric Rice Cooker",
      description: "Multi-function rice cooker for hassle-free cooking.",
      Price: 89.99,
      Category: "Kitchen",
      image: "public/cooker.jpg",
    },
    {
      title: "Cookware Set",
      description: "Non-stick cookware set for everyday cooking.",
      Price: 149.99,
      Category: "Kitchen",
      image: "public/cooker.jpg",
    },
    {
      title: "Water Bottle",
      description: "Insulated stainless steel water bottle for travel and gym.",
      Price: 24.99,
      Category: "Fitness",
      image: "public/cooker.jpg",
    },
    {
      title: "Yoga Blocks",
      description: "High-density yoga blocks for improved flexibility and balance.",
      Price: 18.99,
      Category: "Fitness",
      image: "public/yoga.jpg",
    },
    {
      title: "Picnic Basket",
      description: "Classic woven picnic basket with storage compartments.",
      Price: 59.99,
      Category: "Outdoor",
      image: "public/basket.jpg",
    }
  ];

  const productsWithImages = products.map((item) => ({
    ...item,
    image: resolveProductImage(item.image) || null,
  }));

  const productsWithVectors = await Promise.all(productsWithImages.map(async (product) => {
    const embedding = await generateVector(product.title + " " + product.description + " " + product.Category);
    return {
      ...product,
      embedding
    };
  }));

  await product.insertMany(productsWithVectors);

  return Response.json({ message: "Products seeded successfully" });
}